node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    def scannerHome = tool 'SonarScanner';
    withSonarQubeEnv() {
      sh "${scannerHome}/bin/sonar-scanner"
    }
  }
}
 
    // stage('sonar-scanner') {
    //   def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
    //   withCredentials([string(credentialsId: 'sonar', variable: 'sonarLogin')]) {
    //     sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=export-to-google -Dsonar.projectVersion=${env.BUILD_NUMBER}  -Dsonar.projectKey=GS -Dsonar.sources=. -Dsonar.projectBaseDir=/var/jenkins_home/workspace/sonar -Dsonar.sourceEncoding=UTF-8
    //   -Dsonar.language=js -Dsonar.nodejs.executable=/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS/bin/node"
        
    //   }
    // }
       
